# Generated by Django 5.0.6 on 2024-06-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_author_user_quote_user_tag_user_tag_tag_of_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag of username',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
